version: '3'
services:
  lint:
    image: buildkite/plugin-linter:latest
    command: ['--id', 'JuliaCI/merge-commit']
    volumes:
      - ".:/plugin:ro"
  # test:
  #   build:
  #     context: tests
  #     dockerfile: Dockerfile
  #   volumes:
  #     - ".:/plugin:ro"
